#!/bin/bash

# usually agent hooks directory is in /etc/buildkite-agent/hooks

# The `environment` hook will run before all other commands, and can be used
# to set up secrets, data, etc. Anything exported in hooks will be available
# to the build script.
#
# For example:
#
# export SECRET_VAR=token

# Note that as the script is sourced not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

exec 3<> /dev/null
function magenta {
    printf "+++ \e[35m$1\e[0m\n"
}
{ magenta "agent environment"; } 2>&3

__DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

/bin/bash "$__DIR/pre-command" env