# Some code changes, such as editing a Readme, may not require a Buildkite build. If you want Buildkite to ignore a commit, add [ci skip] or [skip ci] anywhere in the commit message.


agents:
  queue: machine-registry
  
steps:
#  - label: writeaccess
#    commands:
#      - /bin/bash ../cypress-clean/run_as_root.sh
#
#    agents:
#      queue: machine-buildkite
#    WARNING ADD THIS STEP TO PIPELINE CONFIGURATION
#
#  - wait

  - label: test
    key: test
    commands:
      - /bin/bash .buildkite/test.sh
